### ISSUE TITLE
Install Ocaml-Torch failed on macos with M1 chip

### ISSUE THREAD

**Issue by Murphy-OrangeMud** [LaurentMazare/ocaml-torch#76]
Ocaml version: 4.14.0/5.0.0~beta1
OS: Mac OS X 12.4
arch: arm64

```
[ERROR] The compilation of torch.0.10 failed at "dune build -p torch -j 7".

#=== ERROR while compiling torch.0.10 =========================================#
# context     2.1.3 | macos/arm64 | ocaml-base-compiler.4.14.0 | https://opam.ocaml.org#9262cfc7
# path        ~/.opam/4.14.0/.opam-switch/build/torch.0.10
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p torch -j 7
# exit-code   1
# env-file    ~/.opam/log/torch-44603-e773ab.env
# output-file ~/.opam/log/torch-44603-e773ab.out
### output ###
# [...]
# ./torch_api_generated.cpp.h:403:29: error: no member named '_cumsum_out' in namespace 'torch'; did you mean 'cumsum_out'?
#     auto outputs__ = torch::_cumsum_out(*out, *self, dim);
#                      ~~~~~~~^~~~~~~~~~~
#                             cumsum_out
# ./torch_api.h:14:5: note: expanded from macro 'PROTECT'
#     x \
#     ^
# /Users/murphycheng/opt/anaconda3/lib/python3.9/site-packages/torch/include/ATen/ops/cumsum.h:31:31: note: 'cumsum_out' declared here
# TORCH_API inline at::Tensor & cumsum_out(at::Tensor & out, const at::Tensor & self, int64_t dim, c10::optional<at::ScalarType> dtype=c10::nullopt) {
#                               ^
# fatal error: too many errors emitted, stopping now [-ferror-limit=]
# 20 errors generated.

```

**Comment by vthemelis** [comment]
@Murphy-OrangeMud , did you manage to resolve this issue? I'm having a similar issue at the moment.

**Comment by vthemelis** [comment]
There are a few issues with installing this on an M1 Mac but here are the steps:
* Download `libtorch` binaries (or build `libtorch` in your Mac). At the moment there are no official pre-build binaries. I downloaded my (unofficial) binaries from https://github.com/mlverse/libtorch-mac-m1/releases .
* Double check what libtorch version is compatible with the current version of `torch`. Version 1.13.1 is the one you want with v0.16.0 version of torch.
* Set the `LIBTORCH` environment variable to the directory that includes the include and lib directories.
* Use the latest JaneStreet fork of this. Have a look at https://opam.ocaml.org/packages/torch/ for the current version.
* * This may require a newer OCaml version so check for that.
* * To install with `opam`:
```
opam install torch.v0.16.0 --ignore-constraints-on libtorch
```

Note that I had to `ignore-constraints` to avoid failing because `libtorch` is disabled for M1 Mac. Note also that I explicitly had to set the version of the package (JaneStreet version starts with `v0` rather than `0`) as I otherwise resolve to version 0.10 which is way too old.
