### ISSUE TITLE
How to extend Tensor.t with additional functions?

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [LaurentMazare/ocaml-torch#83]
I'm interested in adding [FP8 bindings](https://github.com/Tiiiger/QPyTorch/tree/master/qtorch/quant/quant_cpu) to this library. 

How should I extend the existing bindings? I'm attempting to extend Torch.Tensor module with additional bindings(to custom cpp code)

OCaml compiler is unable to match the types in this line. https://github.com/ArulselvanMadhavan/quantviz/blob/qpytorch/external/qtorch/core/qtensor.ml#L10

```ocaml
File "external/qtorch/core/qtensor.ml", line 10, characters 40-41:
10 |     let result = C.Tensor.tensor_to_int t in
                                             ^
Error: This expression has type t but an expression was expected of type
         unit Ctypes_static.ptr = (unit, [ `C ]) Qtorch_generated.CI.pointer
make: *** [Makefile:22: watch] Error 130   
```

 If you were to add additional bindings(outside of libtorch) to Tensor.t, how would you go about it?

**Comment by LaurentMazare** [comment]
I'm not sure to understand exactly what the issue is here / what you're trying to do. If the main missing bit is the type equality between `Tensor.t` and `unit Ctypes_static.ptr`, I would be ok with adding some conversion function to ocaml-torch to make this use case possible (though not expose the type equality as it would easily lead to segfaults/...), e.g. in the [Tensor module](https://github.com/LaurentMazare/ocaml-torch/blob/da2d4244382f70cc9f1c6255c06c443099d1c504/src/wrapper/wrapper.mli#L12), this would provide the following:
```ocaml
    type t
    val to_raw_pointer : t -> unit Ctypes_static.ptr
    val of_raw_pointer : unit Ctypes_static.ptr -> t
```
And hopefully you can use the raw pointer for whatever you want then?

**Comment by ArulselvanMadhavan** [comment]
Thank you @LaurentMazare! I submitted a PR with the suggested functions - https://github.com/LaurentMazare/ocaml-torch/pull/84

**Comment by LaurentMazare** [comment]
Great, thanks for the PR!
